version: "3.9"

services:
  scrapy:
    build: .
    container_name: scrapy
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    volumes:
      - .:/app
    command: scrapy crawl workplacespider